### ISSUE TITLE
Páginas con publicidad

### ISSUE THREAD

**Issue by SidVal** [SidVal/hide-ads#1]
## Investigación & Desarrollo

Parte de la idea para frenar a las páginas que hacen el `reload()` via JS y vuelven a recargar toda la publicidad es detectar el cambio a nivel DOM y frenar cualquier script que se quiera ejecutar.

- [Detecting DOM changes](http://craigfreeman.net/blog/2014/02/detecting-dom-changes/) 
- [How JavaScript works: tracking changes in the DOM using MutationObserver](https://blog.sessionstack.com/how-javascript-works-tracking-changes-in-the-dom-using-mutationobserver-86adc7446401)
- [Detect changes in the DOM - stackoverflow](https://stackoverflow.com/questions/3219758/detect-changes-in-the-dom)

***

## Testing a la Version 0.01

Tener en cuenta los [selectores de id con regex](https://sidval.github.io/dev.web/#/u/unidad2?id=selector-de-atributo-de-valor-de-subcadena) para captar publicidad y eliminarla desde [`styles.css`](https://github.com/SidVal/hide-ads/blob/master/style.css).

Tener en cuenta también el código que mata con el botón del [`feedly-no-img.css`](https://github.com/SidVal/feedly-no-img/blob/master/docs/assets/feedly-no-img.css)

***

Para testing, usar:
`https://rawgit.com/SidVal/hide-ads/master/style.css`

Botón de testing:
```
javascript:(function()%7B(function(i%2Cn%2Cj%2Ce%2Cc%2Ct%2Ccss)%7B css%3Di.createElement(n)%3Bt%3Di.getElementsByTagName(c)%5B0%5D%3Bcss.href%3Dj%3Bcss.rel%3De%3B t.insertAdjacentElement('beforeend'%2Ccss)%3B%7D) (document%2C'link'%2C'https%3A%2F%2Frawgit.com%2FSidVal%2Fhide-ads%2Fmaster%2Fstyle.css'%2C'stylesheet'%2C'head')%7D)()
```

Para cuando haya versión final, cargar en: https://rawgit.com/
`https://github.com/SidVal/hide-ads/blob/master/style.css`

### Lista de páginas con publicidad

- iProfesional - [_(Análisis)_](https://github.com/SidVal/hide-ads/issues/1#issuecomment-409900091)
- elEstimulo - [_(Análisis)_](https://github.com/SidVal/hide-ads/issues/1#issuecomment-409900558)
- Forbes - [_(Análisis)_](https://github.com/SidVal/hide-ads/issues/1#issuecomment-410235704)
- elEconomista - [_(Análisis)_](https://github.com/SidVal/hide-ads/issues/1#issuecomment-413511580)
- LaNación - [_(Análisis)_](https://github.com/SidVal/hide-ads/issues/1#issuecomment-415383217)
- Ámbito - [_(Análisis)_](https://github.com/SidVal/hide-ads/issues/1#issuecomment-458650426)

***

### Migrado contenido a GitHub Pages porque:
>RawGit has reached the end of its useful life

**Comment by SidVal** [comment]
## iProfesional

Ver ejemplo [sección tecnología](http://www.iprofesional.com/tecnologia).

**Comment by SidVal** [comment]
## elEstimulo

Web Insoportable con ads de videos con frame flotante lateral cada "x" segundos.  

[Ejemplo 1](http://elestimulo.com/elinteres/como-llego-y-salio-argentina-de-la-hiperinflacion/).

Se alimenta con éste css:
`http://dkae4asr0dphj.cloudfront.net/css/lo_vslider.min.css`

**Comment by SidVal** [comment]
## Forbes.com

Interesante la publicidad de forbes.
Posee ademas de los ads comunes (en sidebar), un video-sticky muy mal, que tapa el contenido del lado izquierdo.

Usa un elemento propio parece, un `<fbs-video ...></fbs-video>`.

**Comment by SidVal** [comment]
## LaNacion

Página testing: https://www.lanacion.com.ar/2164721-que-es-extincion-dominio

Hay una imagen muy interesante que carga vía iframe, parece no estar funcionando la versión actual que uso.

Imagen:

```html
<img src="https://s.adroll.com/a/V7S/QO4/V7SQO4KE2ZEC7EG3I4DLJV.jpg" width="300" height="600" border="0" alt="" style=" _width:298px; _height:598px; _overflow:hidden; border:1px solid #000000;margin:-1px;">
```

Versión actual:
```css
[id^=LO_VS], 
div [id*=banner], 
div [id*=ad],
div [id*=anner],
div [id*=lx] ins img,
div [id*=lx] ins iframe,
div [id*=lx] ins,
div [id*=lx],
div [id*=google] ins img,
div [class*=google],
div [class^=video], 
div [class*=ad],
img [class*=ad],
iframe [id*=ads],
[data-ad-format],
[data-variation]
{visibility:hidden;}
div [id*=conten] {background-color: #ffffff7d}
html {cursor:unset !important}
body {background-image: none !important;background-color: #d9d9d9 !important}
```

**Comment by SidVal** [comment]
Con la versión actual, que a mi modo de ver podría depurar, hay sitios que pasan prueba bien

Versión actual: 

```css
[id^=LO_VS], 
div [id*=banner], 
div [id*=ad],
div [id*=anner],
div [id*=lx] ins img,
div [id*=lx] ins iframe,
div [id*=lx] ins,
div [id*=lx],
div [id*=google] ins img,
div [class*=google],
div [class^=video], 
div [class*=ad],
img [class*=ad],
img [src*=ad],
iframe,
[data-ad-format],
[data-variation]
{visibility:hidden;}
div [id*=conten] {background-color: #ffffff7d}
html {cursor:unset !important}
body {background-image: none !important;background-color: #d9d9d9 !important}
```

Sitios testeados:

* laNación - OK
* elEconomista - OK
* Forbes - OK
* elEstimulo - No OK
* iProfesional -  OK

### elEstimulo 

Si bien esta versión borra todos los ads, me deja un cuadro visible que es muy molesto:
`<div id="g367CB268B1094004A3689751E7AC568FFloatingBanner0" data-inf-ignore="true" style="" class="presented">`
Ver por qué ese `div id` no se borra. 👎

**Comment by SidVal** [comment]
## Ámbito

Interesante cantidad de publicidad: https://www.ambito.com/contenidos/dolar.html

Ámbito usa estos class para banners:

- `banner-wrapper free-banner`
- `banner-wrapper banner-side-left`
- `banner-wrapper banner-side-right`
- `banner-wrapper horizontal`
- ``

**Comment by SidVal** [comment]
Versión final:

```css
[id^=LO_VS], 
div [id*=banner], 
div [id^=ad],
div [id*=anner],
div [id*=lx] ins img,
div [id*=lx] ins iframe,
div [id*=lx] ins,
div [id*=lx],
div [id*=google] ins img,
div [class*=google],
div [class^=video], 
div [class^=ad],
div [class*=banner],
img [class*=ad],
img [src^=ad],
iframe,
[data-ad-format],
[data-variation]
{display: none !important;}
div [id*=conten] {background-color: #ffffff7d}
html {cursor:unset !important}
body {background-image: none !important;background-color: #d9d9d9 !important}
```

Verificado en ámbito, funciona bien.

**Comment by SidVal** [comment]
Quito estas cosas:

```css
div [id*=conten] {background-color: #ffffff7d}
body {background-image: none !important;background-color: #d9d9d9 !important}
```

No lo veo necesario. No sé en base a qué se los agregué.
